#!/usr/bin/env python3
"""Harvest WHOIS servers from IANA, verify them, and refresh `whois.json`.

Nothing here trusts IANA's word for it. A server only reaches `whois.json`
after this script has, for that exact TLD:

  1. resolved the host and got an answer out of it on port 43;
  2. asked it about a 16-character random label nobody can have registered,
     and had the answer read as AVAILABLE;
  3. asked it about a name proven registered *independently of WHOIS* — the
     name has NS records in the DNS — and had the answer read as TAKEN;
  4. found a needle for the "free" answer from a hand-vetted list of real
     registry phrasings, and confirmed that needle is absent (unnegated) from
     the "taken" answer.

Step 4 is allowed to come up empty: `available` is then left as `""`, which
makes `ds` fall back to the same generic markers it already uses for a server
discovered through an IANA referral at runtime. What never happens is a
*guessed* needle — a wrong needle reports a registered domain as AVAILABLE,
and that is the one mistake this project refuses to make.

The verdicts are produced by `whois_classify.py`, a line-for-line port of
`classify()` in `src/whois.rs`, so "reads as AVAILABLE" means what `ds` itself
would decide when handed that response.

Stages (all cached under scripts/.whois-cache/, so a re-run is cheap):

    ./scripts/refresh-whois.py discover   # IANA TLD list + whois: host per TLD
    ./scripts/refresh-whois.py probe      # DNS + the two WHOIS probes per TLD
    ./scripts/refresh-whois.py merge      # verdicts -> whois.json + report
    ./scripts/refresh-whois.py all        # all three

    cargo build --release
    ./scripts/refresh-whois.py verify     # re-check the table through ds itself

Being a good citizen is the point of the pacing knobs. Queries to one registry
are serialised with a gap between them (--host-gap, default 1.5s), and the key
is the *address* the server resolves to rather than its name — hundreds of
`whois.nic.<tld>` aliases sit on a handful of shared back ends, and pacing by
name would let this script hammer one machine from twenty directions at once.
At most --jobs hosts are in flight, and a back end that fails repeatedly is
rested rather than retried into the ground. A slower polite run is the correct
trade; expect the whole thing to take hours.
"""

from __future__ import annotations

import argparse
import json
import random
import re
import socket
import string
import struct
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from whois_classify import (  # noqa: E402
    AVAILABLE,
    TAKEN,
    UNKNOWN,
    classify,
    contains_unnegated,
    format_query,
    normalize,
)

REPO = Path(__file__).resolve().parent.parent
WHOIS_JSON = REPO / "whois.json"
CACHE = Path(__file__).resolve().parent / ".whois-cache"
REPORT = Path(__file__).resolve().parent / "whois-report.tsv"

IANA_TLD_LIST = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt"
IANA_WHOIS = "whois.iana.org"

# Public resolvers for the "is this name registered?" check. Two of them, so a
# single unreachable resolver does not silently turn every name into "free".
RESOLVERS = ["1.1.1.1", "8.8.8.8"]

# Names tried, in order, when looking for a registered domain under a TLD. ICANN
# requires every gTLD registry to run `nic.<tld>`, which is why it leads; the
# rest cover ccTLDs and the older gTLDs.
TAKEN_CANDIDATES = [
    "nic",
    "whois",
    "registry",
    "www",
    "home",
    "web",
    "mail",
    "email",
    "shop",
    "news",
    "about",
    "careers",
    "global",
    "corporate",
    "domain",
    "google",
    "microsoft",
    "apple",
    "amazon",
    "facebook",
    "wikipedia",
    "yahoo",
]

# Hand-vetted "this name is not registered" phrasings, longest/most specific
# first. Every one of these was read out of a real registry's answer to this
# script and judged, by eye, to say only that — nothing here is generated by
# diffing the two responses, because a phrase picked that way is a guess
# wearing a lab coat, and a wrong needle means a registered domain reported
# AVAILABLE.
#
# Each candidate still has to survive `pick_needle`: present unnegated in the
# free answer, absent from the registered one, and driving both classifications
# the right way. A phrase in this list is therefore a *candidate*, never a
# licence.
NEEDLE_CANDIDATES = [
    "no information was found matching that query",
    "no entries found for the selected source",
    "the queried object does not exist",
    "this domain name has not been registered",
    "has not been registered",
    "domain name not known",
    "no such domain",
    "no object found",
    "no matching record",
    "no record found",
    "no match for",
    "not found in database",
    "domain not found",
    "no entries found",
    "no data found",
    "nothing found",
    "no information available about domain name",
    "is available for registration",
    "available for registration",
    "free for registration",
    "domain status: free",
    "status: free",
    "status: available",
    "status: not registered",
    "registration status: available",
    "is not registered",
    "not registered",
    "does not exist",
    "no match",
    "not found",
    "is free",
]

STOP = threading.Event()


# --------------------------------------------------------------------------
# tiny helpers
# --------------------------------------------------------------------------


def log(msg: str) -> None:
    print(msg, file=sys.stderr, flush=True)


def read_json(path: Path, default=None):
    if not path.exists():
        return default
    with path.open() as fh:
        return json.load(fh)


def write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w") as fh:
        json.dump(data, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    tmp.replace(path)


def random_label(n: int = 16) -> str:
    alphabet = string.ascii_lowercase + string.digits
    # Never start with a digit or end with a hyphen; some registries reject
    # such queries outright and the refusal would be read as a dead server.
    return random.choice(string.ascii_lowercase) + "".join(
        random.choice(alphabet) for _ in range(n - 1)
    )


# --------------------------------------------------------------------------
# per-host pacing
# --------------------------------------------------------------------------


class HostPacer:
    """One in-flight query per *backend*, with a minimum gap between them.

    Pacing by hostname is not enough to be polite. Nearly every gTLD publishes
    its own `whois.nic.<tld>`, but hundreds of those are CNAMEs onto a handful
    of shared registry back ends — Identity Digital, CentralNic, GoDaddy
    Registry. Treating them as separate hosts would let this script hammer one
    machine from twenty directions at once. So the pacing key is the address
    the name resolves to, and every TLD sharing a back end queues behind the
    same gap.
    """

    # Consecutive failures before a back end is rested, and for how long.
    # Resting rather than dropping matters: hundreds of TLDs can sit behind one
    # address, and a minute of rate limiting must not disqualify all of them
    # for the rest of the run.
    GIVE_UP_AFTER = 4
    COOLDOWN = 120.0

    def __init__(self, gap: float):
        self.gap = gap
        self._lock = threading.Lock()
        self._locks: dict[str, threading.Lock] = {}
        self._last: dict[str, float] = {}
        self._fails: dict[str, int] = {}
        self._rested_until: dict[str, float] = {}
        self._keys: dict[str, str] = {}

    def key(self, host: str) -> str:
        """The back end `host` sits on, falling back to the name itself."""
        with self._lock:
            cached = self._keys.get(host)
        if cached is not None:
            return cached
        try:
            key = socket.gethostbyname(host)
        except OSError:
            key = host
        with self._lock:
            self._keys[host] = key
        return key

    def _lock_for(self, host: str) -> threading.Lock:
        with self._lock:
            return self._locks.setdefault(host, threading.Lock())

    def dead(self, host: str) -> bool:
        """Is this back end resting after a run of failures?"""
        key = self.key(host)
        with self._lock:
            return time.monotonic() < self._rested_until.get(key, 0.0)

    def note(self, host: str, ok: bool) -> None:
        key = self.key(host)
        with self._lock:
            if ok:
                self._fails[key] = 0
                return
            fails = self._fails.get(key, 0) + 1
            self._fails[key] = fails
            if fails >= self.GIVE_UP_AFTER:
                # Rest it, and come back with the counter one short of the
                # threshold so a single further failure rests it again.
                self._rested_until[key] = time.monotonic() + self.COOLDOWN
                self._fails[key] = self.GIVE_UP_AFTER - 1

    def __call__(self, host: str):
        return _Paced(self, host)


class _Paced:
    def __init__(self, pacer: HostPacer, host: str):
        self.pacer, self.host = pacer, pacer.key(host)

    def __enter__(self):
        self.lock = self.pacer._lock_for(self.host)
        self.lock.acquire()
        last = self.pacer._last.get(self.host)
        if last is not None:
            wait = self.pacer.gap - (time.monotonic() - last)
            if wait > 0:
                time.sleep(wait)
        return self

    def __exit__(self, *exc):
        self.pacer._last[self.host] = time.monotonic()
        self.lock.release()
        return False


# --------------------------------------------------------------------------
# WHOIS over port 43
# --------------------------------------------------------------------------


def whois_query(host: str, query: str, timeout: float = 15.0) -> str:
    sock = socket.create_connection((host, 43), timeout)
    try:
        sock.settimeout(timeout)
        sock.sendall(query.encode("utf-8", "replace"))
        chunks, total = [], 0
        deadline = time.monotonic() + timeout
        while total < 256 * 1024:
            if time.monotonic() > deadline:
                break
            data = sock.recv(8192)
            if not data:
                break
            chunks.append(data)
            total += len(data)
    finally:
        sock.close()
    return b"".join(chunks).decode("utf-8", "replace").replace("\r\n", "\n")


def whois_ask(pacer: HostPacer, host: str, domain: str, retries: int = 2) -> tuple[str | None, str | None]:
    """-> (response, error). Retries only what is worth retrying."""
    if pacer.dead(host):
        return None, "back end resting after repeated failures"
    last_err = None
    for attempt in range(retries + 1):
        if STOP.is_set():
            return None, "interrupted"
        try:
            with pacer(host):
                raw = whois_query(host, format_query(host, domain))
            pacer.note(host, True)
            return raw, None
        except (socket.gaierror,) as e:
            pacer.note(host, False)
            return None, "resolving %s: %s" % (host, e)
        except (ConnectionResetError, socket.timeout, TimeoutError) as e:
            last_err = "%s: %s" % (host, e or type(e).__name__)
            pacer.note(host, False)
            time.sleep(2.0 * (attempt + 1))  # back off; a reset means "slow down"
        except OSError as e:
            pacer.note(host, False)
            return None, "%s: %s" % (host, e)
    return None, last_err or "no answer"


# --------------------------------------------------------------------------
# minimal DNS: does this name have NS records?
# --------------------------------------------------------------------------


def _dns_encode(name: str) -> bytes:
    out = b""
    for label in name.rstrip(".").split("."):
        raw = label.encode("idna") if any(ord(c) > 127 for c in label) else label.encode()
        out += bytes([len(raw)]) + raw
    return out + b"\0"


def dns_has_ns(name: str, timeout: float = 4.0) -> bool | None:
    """True/False if a resolver answered, None if none of them did.

    NS records at the name itself are proof of a delegation, which for a
    second-level name means somebody registered it. The converse is not true
    (a registered name need not be delegated), which is exactly why this is
    used only to *find* a name that is certainly taken.
    """
    query = struct.pack(">HHHHHH", random.randrange(65536), 0x0100, 1, 0, 0, 0)
    query += _dns_encode(name) + struct.pack(">HH", 2, 1)  # NS, IN
    for server in RESOLVERS:
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            sock.settimeout(timeout)
            try:
                sock.sendto(query, (server, 53))
                data, _ = sock.recvfrom(4096)
            finally:
                sock.close()
        except OSError:
            continue
        if len(data) < 12:
            continue
        _, flags, _, ancount, _, _ = struct.unpack(">HHHHHH", data[:12])
        rcode = flags & 0xF
        if rcode == 3:  # NXDOMAIN
            return False
        if rcode != 0:
            continue
        return ancount > 0
    return None


# --------------------------------------------------------------------------
# stage 1: discover
# --------------------------------------------------------------------------


def bundled_tlds() -> set[str]:
    tlds = set()
    for entry in read_json(WHOIS_JSON, []):
        for ext in entry["extensions"].split(","):
            t = ext.strip().strip(".").lower()
            if t:
                tlds.add(t)
    return tlds


def fetch_iana_tld_list() -> list[str]:
    import urllib.request

    cached = CACHE / "tlds-alpha-by-domain.txt"
    try:
        with urllib.request.urlopen(IANA_TLD_LIST, timeout=30) as resp:
            text = resp.read().decode()
        cached.parent.mkdir(parents=True, exist_ok=True)
        cached.write_text(text)
    except Exception as e:  # noqa: BLE001 - a cached list beats no run at all
        if not cached.exists():
            raise
        log("  IANA list fetch failed (%s) — using cached copy" % e)
        text = cached.read_text()
    return [
        line.strip().lower()
        for line in text.splitlines()
        if line.strip() and not line.startswith("#")
    ]


def parse_iana_record(raw: str) -> dict:
    info: dict[str, str] = {}
    for line in raw.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        key, value = key.strip().lower(), value.strip()
        if not value:
            continue
        if key == "whois" and "whois" not in info:
            info["whois"] = value.lower()
        elif key in ("organisation", "organization") and "organisation" not in info:
            info["organisation"] = value
        elif key == "status" and "status" not in info:
            info["status"] = value
    return info


def stage_discover(args) -> dict:
    """One `whois.iana.org` query per TLD we do not already cover."""
    path = CACHE / "servers.json"
    known: dict = read_json(path, {}) or {}

    all_tlds = fetch_iana_tld_list()
    have = {t.split(".")[-1] for t in bundled_tlds()}
    todo = [t for t in all_tlds if t not in have or args.refresh_known]
    todo = [t for t in todo if t not in known or args.refresh_known]
    if args.only:
        todo = [t for t in todo if t in args.only]

    log(
        "discover: %d TLDs at IANA, %d already covered, %d cached, %d to ask about"
        % (len(all_tlds), len(have), len(known), len(todo))
    )

    pacer = HostPacer(args.iana_gap)
    for i, tld in enumerate(todo, 1):
        if STOP.is_set():
            break
        raw, err = whois_ask(pacer, IANA_WHOIS, tld, retries=2)
        if raw is None:
            log("  %-24s IANA: %s" % (tld, err))
            continue
        known[tld] = parse_iana_record(raw)
        if i % 50 == 0:
            write_json(path, known)
            log("  ... %d/%d" % (i, len(todo)))
    write_json(path, known)

    with_server = sum(1 for v in known.values() if v.get("whois"))
    log("discover: %d records, %d name a WHOIS server" % (len(known), with_server))
    return known


# --------------------------------------------------------------------------
# stage 2: probe
# --------------------------------------------------------------------------


def find_taken_name(tld: str, cache: dict, lock) -> str | None:
    """A name under `tld` that the DNS proves is registered.

    NS records at a second-level name are proof of a delegation, and so proof
    that somebody registered it — evidence that owes nothing to WHOIS, which is
    the point: it is what the WHOIS answer is being checked against.

    The DNS work happens outside the lock. It is slow, and every worker in the
    pool would otherwise queue behind one TLD's walk down the candidate list.
    """
    with lock:
        if cache.get(tld):
            return cache[tld]
    found = None
    # A brand TLD often has only its own name registered under it — `bmw.bmw`,
    # `seat.seat` — so the label is tried alongside the generic candidates.
    for label in [tld.split(".")[-1]] + TAKEN_CANDIDATES:
        if STOP.is_set():
            return None
        name = "%s.%s" % (label, tld)
        if dns_has_ns(name):
            found = name
            break
    # Only successes are cached. A miss usually means the candidate list was
    # too short for this TLD, and remembering it would make a later run with a
    # longer list skip the TLD without looking.
    if found:
        with lock:
            cache[tld] = found
    return found


def probe_one(tld: str, host: str, pacer: HostPacer, taken_cache: dict, lock) -> dict:
    out: dict = {"tld": tld, "host": host}

    free_domain = "%s.%s" % (random_label(), tld)
    out["free_domain"] = free_domain
    raw, err = whois_ask(pacer, host, free_domain)
    if raw is None:
        out["error"] = "free probe: %s" % err
        return out
    out["free_raw"] = raw

    taken_domain = find_taken_name(tld, taken_cache, lock)
    if not taken_domain:
        out["error"] = "no DNS-proven registered name found under .%s" % tld
        return out
    out["taken_domain"] = taken_domain
    raw, err = whois_ask(pacer, host, taken_domain)
    if raw is None:
        out["error"] = "taken probe: %s" % err
        return out
    out["taken_raw"] = raw
    return out


def stage_probe(args, servers: dict) -> dict:
    path = CACHE / "probes.json"
    probes: dict = read_json(path, {}) or {}

    todo = []
    for tld, info in sorted(servers.items()):
        host = info.get("whois")
        if not host:
            continue
        cached = probes.get(tld)
        if cached is not None and not args.reprobe:
            # A probe that failed for a *network* reason says nothing about the
            # server, so --retry-failed picks those up again while leaving the
            # ones that produced a real answer alone.
            if not (args.retry_failed and cached.get("error")):
                continue
        if args.only and tld not in args.only:
            continue
        todo.append((tld, host))

    log("probe: %d TLDs to probe (%d cached)" % (len(todo), len(probes)))

    # Group by host so the pool never has two workers queuing on one registry:
    # each worker owns a whole host's worth of TLDs and walks it at --host-gap.
    by_host: dict[str, list[str]] = {}
    for tld, host in todo:
        by_host.setdefault(host, []).append(tld)
    log("probe: %d distinct hosts" % len(by_host))

    pacer = HostPacer(args.host_gap)
    taken_cache: dict = read_json(CACHE / "taken-names.json", {}) or {}
    lock = threading.Lock()
    done = [0]

    def run_host(host: str):
        for tld in by_host[host]:
            if STOP.is_set():
                return
            result = probe_one(tld, host, pacer, taken_cache, lock)
            with lock:
                probes[tld] = result
                done[0] += 1
                if done[0] % 25 == 0:
                    write_json(path, probes)
                    write_json(CACHE / "taken-names.json", taken_cache)
                    log("  ... %d/%d" % (done[0], len(todo)))

    with ThreadPoolExecutor(max_workers=args.jobs) as pool:
        list(pool.map(run_host, list(by_host)))

    write_json(path, probes)
    write_json(CACHE / "taken-names.json", taken_cache)
    log("probe: %d probe records" % len(probes))
    return probes


# --------------------------------------------------------------------------
# stage 3: judge and merge
# --------------------------------------------------------------------------


def pick_needle(free_raw: str, taken_raw: str, free_domain: str, taken_domain: str):
    """The most specific vetted phrase that says "free" here and never "taken"."""
    free = normalize(free_raw)
    taken = normalize(taken_raw)
    for needle in NEEDLE_CANDIDATES:
        n = normalize(needle)
        if not contains_unnegated(free, n):
            continue
        if contains_unnegated(taken, n):
            continue  # the same phrase shows up in a registered record: useless
        # And it has to actually drive the verdicts the right way.
        if classify(free_raw, needle, free_domain)[0] != AVAILABLE:
            continue
        if classify(taken_raw, needle, taken_domain)[0] != TAKEN:
            continue
        return needle
    return None


def judge(probe: dict) -> dict:
    """-> {verdict, needle, reason}. `verdict` is accept / accept-generic / reject."""
    tld, host = probe["tld"], probe.get("host")
    out = {"tld": tld, "host": host, "needle": "", "verdict": "reject", "reason": ""}

    if probe.get("error"):
        out["reason"] = probe["error"]
        return out

    free_raw, taken_raw = probe.get("free_raw"), probe.get("taken_raw")
    free_domain, taken_domain = probe["free_domain"], probe.get("taken_domain", "")
    if free_raw is None or taken_raw is None:
        out["reason"] = "incomplete probe"
        return out

    # A server that answers both questions identically knows nothing about
    # either name; whatever it says, it cannot tell them apart.
    if free_raw.strip() == taken_raw.strip():
        out["reason"] = "identical answer for a free and a registered name"
        return out

    free_status, free_note = classify(free_raw, "", free_domain)
    taken_status, taken_note = classify(taken_raw, "", taken_domain)

    if taken_status != TAKEN:
        out["reason"] = "registered %s reads as %s (%s)" % (
            taken_domain,
            taken_status.upper(),
            taken_note or "-",
        )
        return out

    needle = pick_needle(free_raw, taken_raw, free_domain, taken_domain)
    if needle:
        out["needle"] = needle
        out["verdict"] = "accept"
        out["reason"] = "needle verified against both probes"
        return out

    if free_status == AVAILABLE:
        out["verdict"] = "accept-generic"
        out["reason"] = "no vetted needle matched; generic markers decide both probes"
        return out

    out["reason"] = "unregistered %s reads as %s (%s)" % (
        free_domain,
        free_status.upper(),
        free_note or "-",
    )
    return out


def stage_merge(args, probes: dict, servers: dict | None = None) -> None:
    verdicts = [judge(p) for p in (probes[k] for k in sorted(probes))]

    # TLDs IANA has no WHOIS server for at all belong in the report too:
    # leaving them out would make it look as though they were never considered.
    # Almost all of them are RDAP-only gTLDs, which `ds` reaches anyway.
    for tld in sorted(servers or {}):
        if tld in probes or (servers[tld] or {}).get("whois"):
            continue
        verdicts.append(
            {
                "tld": tld,
                "host": "",
                "needle": "",
                "verdict": "no-server",
                "reason": "IANA lists no WHOIS server for this TLD",
            }
        )
    verdicts.sort(key=lambda v: v["tld"])
    write_report(verdicts)

    accepted = [v for v in verdicts if v["verdict"].startswith("accept")]
    existing = read_json(WHOIS_JSON, [])
    have = bundled_tlds()

    # Group the new TLDs by (host, needle) so one entry serves many extensions,
    # exactly as the hand-written half of the file already does. This is what
    # keeps the compiled-in table from ballooning.
    groups: dict[tuple[str, str], list[str]] = {}
    for v in accepted:
        if v["tld"] in have:
            continue
        groups.setdefault((v["host"], v["needle"]), []).append(v["tld"])

    added = []
    for (host, needle), tlds in sorted(groups.items(), key=lambda kv: kv[1][0]):
        added.append(
            {
                "extensions": ",".join("." + t for t in sorted(tlds)),
                "uri": "socket://" + host,
                "available": needle,
            }
        )
        have.update(tlds)

    counts = {}
    for v in verdicts:
        counts[v["verdict"]] = counts.get(v["verdict"], 0) + 1
    log(
        "merge: %s"
        % ", ".join("%s %d" % (k, counts[k]) for k in sorted(counts))
    )
    log(
        "merge: %d new entries covering %d new TLDs"
        % (len(added), sum(len(t) for t in groups.values()))
    )

    if args.dry_run:
        log("merge: --dry-run, whois.json untouched")
        return

    write_json(WHOIS_JSON, existing + added)
    log("merge: wrote %s (%d entries)" % (WHOIS_JSON, len(existing) + len(added)))


# --------------------------------------------------------------------------
# stage 4: verify the written table through the real binary
# --------------------------------------------------------------------------


def stage_verify(args, probes: dict) -> int:
    """Re-check `whois.json` end to end, with `ds` itself doing the deciding.

    The merge stage judges responses with the Python port of `classify()`. This
    stage proves the whole chain instead — `whois.json` parsing, the
    longest-suffix lookup, `format_query`, the real classifier — by asking the
    compiled binary about names whose answer is already known: the DNS-proven
    registered name for each TLD must come back TAKEN, and a fresh random label
    must come back AVAILABLE. Anything else is a finding, and a registered name
    reported AVAILABLE is the finding that matters.
    """
    binary = Path(args.binary)
    if not binary.exists():
        log("verify: %s does not exist — run `cargo build --release` first" % binary)
        return 1

    taken_names = read_json(CACHE / "taken-names.json", {}) or {}
    bundled = bundled_tlds()

    pairs = []
    for tld in sorted(bundled):
        registered = taken_names.get(tld)
        if not registered:
            continue  # nothing independently proven to be registered here
        pairs.append((tld, registered, "%s.%s" % (random_label(), tld)))

    if args.only:
        pairs = [p for p in pairs if p[0] in args.only]
    if args.sample and args.sample < len(pairs):
        pairs = random.sample(pairs, args.sample)
    pairs.sort()

    log("verify: %d TLDs, two lookups each, through %s" % (len(pairs), binary))

    expected = {}
    for _, registered, free in pairs:
        expected[registered] = TAKEN
        expected[free] = AVAILABLE

    import subprocess

    def run(domains: list[str], jobs: int, batch: int) -> dict[str, tuple[str, str]]:
        """-> {domain: (status, note)} for one sweep through `ds`."""
        out_map: dict[str, tuple[str, str]] = {}
        for i in range(0, len(domains), batch):
            chunk = domains[i : i + batch]
            cmd = [
                str(binary), *chunk,
                "--source", "whois",
                "--json",
                "--concurrency", str(jobs),
                "--per-host", "1",
                "--no-color",
            ]
            try:
                proc = subprocess.run(cmd, capture_output=True, text=True, timeout=1800)
            except subprocess.TimeoutExpired:
                log("  batch %d: timed out" % (i // batch))
                continue
            try:
                for row in json.loads(proc.stdout or "[]"):
                    notes = row.get("notes") or row.get("note") or ""
                    if isinstance(notes, list):
                        notes = "; ".join(notes)
                    out_map[row["domain"]] = (row["status"].lower(), notes)
            except (json.JSONDecodeError, KeyError, TypeError) as e:
                log("  batch %d: could not read ds output (%s)" % (i // batch, e))
            log("  ... %d/%d" % (min(i + batch, len(domains)), len(domains)))
        return out_map

    results = run(sorted(expected), args.verify_jobs, 40)

    # A sweep this size rate-limits the shared back ends, and `ds` reports a
    # reset connection as UNKNOWN — correctly, but it tells us nothing about
    # the table. Give those a second, much gentler pass before judging.
    unresolved = sorted(
        d for d in expected if results.get(d, (UNKNOWN, ""))[0] == UNKNOWN
    )
    if unresolved and not args.no_retry:
        log("verify: %d unresolved, retrying them gently" % len(unresolved))
        time.sleep(30)
        for domain, outcome in run(unresolved, 2, 12).items():
            if outcome[0] != UNKNOWN:
                results[domain] = outcome

    counts = {"ok": 0, "unknown": 0, "wrong": 0, "missing": 0}
    findings, unresolved_notes = [], []
    for domain, want in sorted(expected.items()):
        entry = results.get(domain)
        if entry is None:
            counts["missing"] += 1
        elif entry[0] == want:
            counts["ok"] += 1
        elif entry[0] == UNKNOWN:
            counts["unknown"] += 1
            unresolved_notes.append((domain, entry[1]))
        else:
            counts["wrong"] += 1
            findings.append((domain, want, entry[0]))

    log(
        "verify: %d agreed, %d disagreed, %d still UNKNOWN, %d no result"
        % (counts["ok"], counts["wrong"], counts["unknown"], counts["missing"])
    )
    for domain, want, got in findings:
        severity = "DANGEROUS" if want == TAKEN and got == AVAILABLE else "wrong"
        log("  %-9s %-40s expected %s, ds said %s" % (severity, domain, want, got))
    if args.show_unknown:
        for domain, note in unresolved_notes:
            log("  unknown   %-40s %s" % (domain, note))
    return 1 if findings else 0


def write_report(verdicts: list[dict]) -> None:
    """One row per TLD considered, so a rejection can be looked up later."""
    rows = ["tld\tverdict\thost\tneedle\treason"]
    for v in verdicts:
        rows.append(
            "%s\t%s\t%s\t%s\t%s"
            % (
                v["tld"],
                v["verdict"],
                v["host"] or "",
                v["needle"],
                re.sub(r"\s+", " ", v["reason"]).strip(),
            )
        )
    REPORT.write_text("\n".join(rows) + "\n")
    log("report: %s (%d rows)" % (REPORT, len(verdicts)))


# --------------------------------------------------------------------------


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument(
        "stage",
        choices=["discover", "probe", "merge", "verify", "all", "report"],
        nargs="?",
        default="all",
    )
    ap.add_argument("--jobs", type=int, default=12, help="hosts probed in parallel")
    ap.add_argument(
        "--host-gap",
        type=float,
        default=1.5,
        help="minimum seconds between two queries to the same WHOIS host",
    )
    ap.add_argument(
        "--iana-gap", type=float, default=0.5, help="seconds between whois.iana.org queries"
    )
    ap.add_argument("--only", help="comma separated TLDs, for testing a few")
    ap.add_argument("--reprobe", action="store_true", help="ignore the probe cache")
    ap.add_argument(
        "--retry-failed",
        action="store_true",
        help="re-probe only the TLDs whose cached probe failed to get an answer",
    )
    ap.add_argument(
        "--refresh-known", action="store_true", help="re-ask IANA about every TLD"
    )
    ap.add_argument("--dry-run", action="store_true", help="do not write whois.json")
    ap.add_argument(
        "--binary",
        default="target/release/ds",
        help="the ds binary the verify stage drives (default target/release/ds)",
    )
    ap.add_argument(
        "--sample",
        type=int,
        default=0,
        help="verify only this many TLDs, chosen at random (default: all of them)",
    )
    ap.add_argument(
        "--verify-jobs", type=int, default=6, help="ds --concurrency during verify"
    )
    ap.add_argument(
        "--no-retry", action="store_true", help="verify: skip the gentle second pass"
    )
    ap.add_argument(
        "--show-unknown",
        action="store_true",
        help="verify: list the lookups that stayed UNKNOWN, with the reason",
    )
    args = ap.parse_args()
    args.only = (
        {t.strip().strip(".").lower() for t in args.only.split(",") if t.strip()}
        if args.only
        else None
    )

    CACHE.mkdir(parents=True, exist_ok=True)

    def on_sigint(*_):
        log("\ninterrupted — finishing in-flight queries and saving the cache")
        STOP.set()

    import signal

    signal.signal(signal.SIGINT, on_sigint)

    servers = read_json(CACHE / "servers.json", {}) or {}
    probes = read_json(CACHE / "probes.json", {}) or {}

    if args.stage in ("discover", "all"):
        servers = stage_discover(args)
    if args.stage in ("probe", "all"):
        probes = stage_probe(args, servers)
    if args.stage == "report":
        stage_merge(argparse.Namespace(**{**vars(args), "dry_run": True}), probes, servers)
    if args.stage in ("merge", "all"):
        stage_merge(args, probes, servers)
    if args.stage == "verify":
        return stage_verify(args, probes)
    return 0


if __name__ == "__main__":
    sys.exit(main())
