//! TLDs where the public cannot register a name at all, from the bundled
//! `private-tlds.json` (regenerated by `scripts/build-private-tlds.mjs`).
//!
//! Most of them are .brand gTLDs — `.aws`, `.google`, `.bmw` — whose registry
//! operator holds every name in the zone itself. A lookup there answers "no
//! such domain" for anything you ask about, which reads as AVAILABLE and is
//! the single most misleading thing this tool could say.
//!
//! Membership is asserted only where there is evidence for it: an ICANN
//! Specification 13 exemption, or an RFC reserving the name. A TLD that is not
//! in the file is not thereby claimed to be registrable — `ds` simply makes no
//! claim about it, and reports whatever the registry said.

use std::collections::HashMap;

use anyhow::Result;
use serde::Deserialize;

use crate::tlds::normalize_tld;

const PRIVATE_TLDS_JSON: &str = include_str!("../private-tlds.json");

#[derive(Debug, Deserialize)]
struct RawFile {
    tlds: Vec<RawEntry>,
}

#[derive(Debug, Deserialize)]
struct RawEntry {
    tld: String,
    kind: String,
    #[serde(default)]
    operator: Option<String>,
    #[serde(default)]
    rfc: Option<String>,
}

/// A closed TLD, together with the evidence for calling it closed.
#[derive(Debug, Clone)]
pub struct PrivateTld {
    /// `brand`, `infrastructure` or `reserved`. Kept as the string the data
    /// file uses so a new kind is a data change, not a code change.
    pub kind: String,
    /// For a brand TLD, the registry operator — the only party that can hold a
    /// name in the zone.
    pub operator: Option<String>,
    /// For an IETF-reserved name, the RFC that reserves it.
    pub rfc: Option<String>,
}

impl PrivateTld {
    /// Why the name cannot be registered, phrased to sit on a result line.
    pub fn reason(&self, tld: &str) -> String {
        let apex = apex(tld);
        match self.kind.as_str() {
            "brand" => match &self.operator {
                Some(op) => format!(
                    ".{apex} is a brand TLD — only {op} registers names there (ICANN Spec 13)"
                ),
                None => format!(
                    ".{apex} is a brand TLD — its registry registers names only for itself \
                     (ICANN Spec 13)"
                ),
            },
            "infrastructure" => format!(
                ".{apex} is infrastructure — it has no public registrations ({})",
                self.rfc.as_deref().unwrap_or("IANA")
            ),
            _ => format!(
                ".{apex} is reserved — it can never be registered ({})",
                self.rfc.as_deref().unwrap_or("IETF")
            ),
        }
    }
}

pub struct PrivateTlds {
    by_tld: HashMap<String, PrivateTld>,
}

impl PrivateTlds {
    pub fn load() -> Result<Self> {
        let raw: RawFile = serde_json::from_str(PRIVATE_TLDS_JSON)?;
        Ok(Self {
            by_tld: raw
                .tlds
                .into_iter()
                .map(|e| {
                    (
                        normalize_tld(&e.tld),
                        PrivateTld {
                            kind: e.kind,
                            operator: e.operator,
                            rfc: e.rfc,
                        },
                    )
                })
                .collect(),
        })
    }

    /// Every entry is a whole TLD, so anything under one is equally closed:
    /// the last label decides, as it does for the IANA record of a TLD.
    pub fn lookup(&self, tld: &str) -> Option<&PrivateTld> {
        self.by_tld.get(apex(&normalize_tld(tld)))
    }

    pub fn contains(&self, tld: &str) -> bool {
        self.lookup(tld).is_some()
    }
}

/// `co.uk` -> `uk`, `com` -> `com`.
fn apex(tld: &str) -> &str {
    tld.rsplit('.').next().unwrap_or(tld)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_bundled_file_parses_and_is_the_expected_size() {
        let n = PrivateTlds::load().unwrap().by_tld.len();
        // ~370 live Specification 13 brands plus the handful of IETF names. A
        // regeneration that halves or doubles that is a bug in the generator,
        // not a change in the root zone.
        assert!((300..800).contains(&n), "{n} entries");
    }

    #[test]
    fn knows_brand_tlds() {
        let p = PrivateTlds::load().unwrap();
        for tld in ["aws", "google", "bmw", "apple", "microsoft"] {
            let entry = p.lookup(tld).unwrap_or_else(|| panic!(".{tld}"));
            assert_eq!(entry.kind, "brand");
            assert!(entry.operator.is_some(), ".{tld} has no operator");
        }
        assert_eq!(
            p.lookup("aws").unwrap().operator.as_deref(),
            Some("AWS Registry LLC")
        );
    }

    #[test]
    fn leaves_open_tlds_alone() {
        let p = PrivateTlds::load().unwrap();
        // .app and .dev are Google-run but have no Specification 13: anyone
        // can buy one, and the classification has to reflect that.
        for tld in [
            "com", "net", "org", "io", "de", "co.uk", "app", "dev", "xyz",
        ] {
            assert!(!p.contains(tld), ".{tld} must not be treated as private");
        }
    }

    #[test]
    fn reserved_names_carry_their_rfc() {
        let p = PrivateTlds::load().unwrap();
        assert_eq!(p.lookup("arpa").unwrap().kind, "infrastructure");
        assert_eq!(p.lookup("test").unwrap().rfc.as_deref(), Some("RFC 2606"));
    }

    #[test]
    fn matches_on_the_last_label_and_normalises() {
        let p = PrivateTlds::load().unwrap();
        assert!(p.contains(".AWS"));
        assert!(
            p.contains("corp.aws"),
            "a suffix under a brand TLD is closed too"
        );
        assert!(!p.contains("aws.com"), "the last label is what decides");
    }

    #[test]
    fn explains_itself() {
        let p = PrivateTlds::load().unwrap();
        let brand = p.lookup("aws").unwrap().reason("aws");
        assert!(
            brand.contains("AWS Registry LLC") && brand.contains("Spec 13"),
            "{brand}"
        );
        assert!(p
            .lookup("arpa")
            .unwrap()
            .reason("arpa")
            .contains("RFC 3172"));
    }
}
